name: Build
on:
  workflow_dispatch: # This line enables manual triggering of the workflow
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Analyze
    runs-on: sonarsource/sonar-scanner-cli:11.0.0.1541_6.1.0
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Scan
        run: >
          sonar-scanner
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # SonarQube URL is stored in a GitHub secret
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
